# Generated by cucumber-sinatra. (2014-10-07 11:34:29 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/bookmarkmanager.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = BookMarkManager

class BookMarkManagerWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  BookMarkManagerWorld.new
end
